spring.application.name=eKart

spring.datasource.url=jdbc:mysql://localhost:3306/e_kart
spring.datasource.username=root
spring.datasource.password=mysql

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#jwt
jwt.secret=i10gvYirBwIVVjEYBrGzSC5e47RFA7JNT4za2VCBsIQ=

# ===============================
# RabbitMQ Connection Settings
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# Application RabbitMQ Settings
# ===============================
rabbitmq.exchange=user.exchange
rabbitmq.queue=user.email.queue
rabbitmq.routing-key=user.email

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#
#spring.security.user.name=admin
#spring.security.user.password={noop}password